version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      gatsby:
        patterns:
          - gatsby
          - 'gatsby-*'
      react:
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      all:
        patterns:
          - '*'
